version: 2

workflows:
  version: 2
  quality-tools:
    jobs:
      - unit-tests
      - mutation-tests:
          requires:
            - unit-tests
      - phpstan
      - phpcs

jobs:
  unit-tests:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo composer self-update
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make install-ci
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: mkdir -p ~/phpunit
      - run: make test-unit FLAGS="--log-junit ~/phpunit/unit.xml"
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

  mutation-tests:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo composer self-update
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make install-ci
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make test-mutation

  phpstan:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo composer self-update
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make install-ci
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make static-analysis

  phpcs:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo composer self-update
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make install-ci
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make cs-check
