name: Quality checks

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - uses: ./.github/actions/composer-install

      - name: Run unit tests
        run: make test-unit

      - name: Run mutation tests
        run: make test-mutation

      - name: Run integration tests
        run: make test-integration

  static-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - uses: ./.github/actions/composer-install

      - name: Run static analysis
        run: make static-analysis

  style-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - uses: ./.github/actions/composer-install

      - name: Run style checker
        run: make cs-check

  composer-require-checker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - uses: ./.github/actions/composer-install

      - name: Run ComposerRequireChecker
        run: make composer-require-checker

